import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'



const poppi = Poppins({
  subsets: ['latin'],
  weight: ["200","600"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppi.className}>
      <body>
        
        {children}
      </body>
    </html>
  );
}
